// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PaseoExpressWebApp.Context
{
    public partial class ObtenerServiciosProximoCambioResult
    {
        public string Titulo { get; set; }
        public long? MillajeActual { get; set; }
        public long? ProximoMillaje { get; set; }
        public long? DiferenciaMillas { get; set; }
    }
}
