// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PaseoExpressWebApp.Context
{
    public partial class ObtenerVehiculosResult
    {
        public int IdVehiculo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public int? Anio { get; set; }
        public string VIN { get; set; }
        public string Placa { get; set; }
        public long? Kilometraje { get; set; }
        public long? Millaje { get; set; }
        public string Color { get; set; }
        public int TarifaDiaria { get; set; }
        public int TarifaAhorro { get; set; }
        public string Propietario { get; set; }
        public int? IdConductor { get; set; }
        public string Nombre { get; set; }
    }
}
