// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PaseoExpressWebApp.Context
{
    public partial class ObtenerTransaccionesPorVehiculoResult
    {
        public string Imagen { get; set; }
        public int? UltimaSuma { get; set; }
        public string Conductor { get; set; }
        public int TarifaDiaria { get; set; }
        public int TarifaAhorro { get; set; }
        public DateTime FechaTransaccion { get; set; }
        public string Comentario { get; set; }
    }
}
