// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PaseoExpressWebApp.Context
{
    public partial class ObtenerServiciosResult
    {
        public int IdServicios { get; set; }
        public int IdTipoServicio { get; set; }
        public string TipoServicio { get; set; }
        public string Imagenes { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public DateTime FechaServicio { get; set; }
        [Column("CostoTotal", TypeName = "decimal(10,2)")]
        public decimal? CostoTotal { get; set; }
        public string Marca { get; set; }
        public int IdTipoMantenimiento { get; set; }
        public string Nombre { get; set; }
        public int? MillajeVehiculo { get; set; }
        public DateTime? ProximaFechaMantenimiento { get; set; }
        public int IdVehiculo { get; set; }
        public string VehiculoMarca { get; set; }
        public string VehiculoModelo { get; set; }
        public int? VehiculoAnio { get; set; }
        public bool EsRecurrente { get; set; }
        public long? ProximoMillaje { get; set; }
        public int? IdUbicacionEnAutomovil { get; set; }
        public string UbicacionEnAutomovil { get; set; }
        [Column("PrecioManoObra", TypeName = "decimal(10,2)")]
        public decimal? PrecioManoObra { get; set; }
        public bool Confirmado { get; set; }
        public string Viaticos { get; set; }
        public int? ManoObraPersonal { get; set; }
    }
}
