// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PaseoExpressWebApp.Context
{
    public partial class PR_Chat_ObtenerUltimoMensajePorUsuarioResult
    {
        public int IdUsuario { get; set; }
        public string Imagen { get; set; }
        public string Usuario { get; set; }
        public string Nombre { get; set; }
        public string TagMensajeria { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string Ciudad { get; set; }
        public int IdDetail { get; set; }
        public int SenderId { get; set; }
        public int ReceiverId { get; set; }
        public int? GroupId { get; set; }
        public DateTime? Timestamp { get; set; }
        public int IdMessage { get; set; }
        public string Description { get; set; }
        public bool IsRead { get; set; }
        public DateTime Time { get; set; }
    }
}
