// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PaseoExpressWebApp.Context
{
    public partial class PR_ObtenerVehiculosSinExistenciaHoyResult
    {
        public int IdVehiculo { get; set; }
        public string ImagenUsuario { get; set; }
        public string ImagenVehiculo { get; set; }
        public int? Anio { get; set; }
        public string Placa { get; set; }
        public int TarifaDiaria { get; set; }
        public int TarifaAhorro { get; set; }
        public string Nombre { get; set; }
    }
}
