// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PaseoExpressWebApp.Context
{
    public partial class PR_ObtenerVehiculoInformacionDashboardResult
    {
        public int IdVehiculo { get; set; }
        public string Imagen { get; set; }
        public string Placa { get; set; }
        public string Marca { get; set; }
        public int? Anio { get; set; }
        public string MarcaAceite { get; set; }
        public long? PorcentajeDesgasteAceite { get; set; }
        public long? PorcentajeDesgasteLlanta1 { get; set; }
        public long? PorcentajeDesgasteLlanta2 { get; set; }
        public long? PorcentajeDesgasteLlanta3 { get; set; }
        public long? PorcentajeDesgasteLlanta4 { get; set; }
        public long? PorcentajeDesgasteFiltroMotor { get; set; }
        public long? PorcentajeDesgasteFiltroCabina { get; set; }
    }
}
