// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PaseoExpressWebApp.Context
{
    public partial class PR_ResumenTotalResult
    {
        public int IdVehiculo { get; set; }
        public int? IngresosTotales { get; set; }
        public int? AhorroTotal { get; set; }
        public int? DiasTrabajados { get; set; }
        public int? TotalDias { get; set; }
    }
}
