// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PaseoExpressWebApp.Context
{
    public partial class PR_VerificandoUsuarioResult
    {
        public int IdUsuario { get; set; }
        public string Imagen { get; set; }
        public int IdRol { get; set; }
        public string NombreRol { get; set; }
        public string Usuario { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string Identidad { get; set; }
        public string Cuenta { get; set; }
        public bool? EstaActivo { get; set; }
    }
}
