// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaseoExpressWebApp.Context
{
    public partial class tbConductoresEli
    {
        public int IdConductor { get; set; }
        public string Nombre { get; set; }
        public int? Identidad { get; set; }
        public string Cuenta { get; set; }
    }
}