// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaseoExpressWebApp.Context
{
    public partial class tbDetail
    {
        public int IdDetail { get; set; }
        public int SenderId { get; set; }
        public int ReceiverId { get; set; }
        public int? GroupId { get; set; }
        public DateTime? Timestamp { get; set; }
        public int IdMessage { get; set; }
        public bool IsRead { get; set; }

        public virtual tbMessage IdMessageNavigation { get; set; }
        public virtual tbUsuarios Receiver { get; set; }
        public virtual tbUsuarios Sender { get; set; }
    }
}