// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaseoExpressWebApp.Context
{
    /// <summary>
    /// Registra el historial de mantenimiento de los vehículos, incluyendo fecha, tipo de mantenimiento, vehículo, kilometraje y costo.
    /// 
    /// 
    /// </summary>
    public partial class tbHistorialMantenimiento
    {
        public int IdMantenimiento { get; set; }
        public int? IdVehiculo { get; set; }
        public DateTime? FechaMantenimiento { get; set; }
        public int? IdTipoMantenimiento { get; set; }
        public string DescripcionMantenimiento { get; set; }
        public int? CantidadComprada { get; set; }
        public decimal? CostoUnitario { get; set; }
        public decimal? CostoTotal { get; set; }
        public decimal? CostoManoObra { get; set; }
        public bool? MiMano { get; set; }
        public int? KilometrajeVehiculo { get; set; }
        public DateTime? ProximaFechaMantenimiento { get; set; }
    }
}