// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaseoExpressWebApp.Context
{
    public partial class tbMessage
    {
        public tbMessage()
        {
            tbDetail = new HashSet<tbDetail>();
        }

        public int IdMessage { get; set; }
        public string Description { get; set; }
        public bool IsRead { get; set; }
        public DateTime Time { get; set; }

        public virtual ICollection<tbDetail> tbDetail { get; set; }
    }
}