// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaseoExpressWebApp.Context
{
    /// <summary>
    /// Idica si se el mensaje sera con codigo o simple.
    /// </summary>
    public partial class tbRol
    {
        public tbRol()
        {
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int IdRol { get; set; }
        public string Nombre { get; set; }
        public bool? UsarCodigoMensaje { get; set; }

        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}