// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaseoExpressWebApp.Context
{
    public partial class tbServicios
    {
        public tbServicios()
        {
            IdTransaccion = new HashSet<tbTransacciones>();
        }

        public int IdServicios { get; set; }
        public int IdTipoServicio { get; set; }
        public string Imagenes { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public DateTime FechaServicio { get; set; }
        public int IdVehiculo { get; set; }
        public int? MillajeVehiculo { get; set; }
        public long? ProximoMillaje { get; set; }
        public decimal? CostoTotal { get; set; }
        public string Marca { get; set; }
        public int IdTipoMantenimiento { get; set; }
        public DateTime? ProximaFechaMantenimiento { get; set; }
        public bool EsRecurrente { get; set; }
        public int? IdUbicacionEnAutomovil { get; set; }
        public decimal? PrecioManoObra { get; set; }
        public bool Confirmado { get; set; }
        public string Viaticos { get; set; }
        public int? ManoObraPersonal { get; set; }

        public virtual tbTipoMantenimientos IdTipoMantenimientoNavigation { get; set; }
        public virtual tbTipoServicios IdTipoServicioNavigation { get; set; }
        public virtual tbVehiculo IdVehiculoNavigation { get; set; }

        public virtual ICollection<tbTransacciones> IdTransaccion { get; set; }
    }
}