// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaseoExpressWebApp.Context
{
    public partial class tbServiciosRecurrentesELI
    {
        public int IdServiciosRecurrentes { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public DateTime? FechaActual { get; set; }
        public DateTime? FechaProxima { get; set; }
    }
}