// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaseoExpressWebApp.Context
{
    public partial class tbTipoMantenimientos
    {
        public tbTipoMantenimientos()
        {
            tbServicios = new HashSet<tbServicios>();
        }

        public int IdTipoMantenimiento { get; set; }
        public string Nombre { get; set; }

        public virtual ICollection<tbServicios> tbServicios { get; set; }
    }
}