// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaseoExpressWebApp.Context
{
    /// <summary>
    /// Contiene los diferentes tipos de mantenimiento vehicular.
    /// </summary>
    public partial class tbTipoMantenimientos
    {
        public tbTipoMantenimientos()
        {
            tbServicios = new HashSet<tbServicios>();
        }

        /// <summary>
        /// Identificador único del tipo de mantenimiento.
        /// 
        /// </summary>
        public int IdTipoMantenimiento { get; set; }
        /// <summary>
        /// Nombre o descripción del tipo de mantenimiento.
        /// </summary>
        public string Nombre { get; set; }

        public virtual ICollection<tbServicios> tbServicios { get; set; }
    }
}