// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaseoExpressWebApp.Context
{
    public partial class tbTipoTransaccion
    {
        public tbTipoTransaccion()
        {
            tbTransacciones = new HashSet<tbTransacciones>();
        }

        public int IdTipoTransaccion { get; set; }
        public string Nombre { get; set; }

        public virtual ICollection<tbTransacciones> tbTransacciones { get; set; }
    }
}