// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaseoExpressWebApp.Context
{
    public partial class tbTipoServicios
    {
        public tbTipoServicios()
        {
            tbServicios = new HashSet<tbServicios>();
        }

        public int IdTipoServicio { get; set; }
        public string Nombre { get; set; }
        public string MillajeCambioRecomendado { get; set; }
        public string KilometrajeCambioRecomendado { get; set; }
        public decimal? Meses { get; set; }

        public virtual ICollection<tbServicios> tbServicios { get; set; }
    }
}