// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaseoExpressWebApp.Context
{
    /// <summary>
    /// Contiene los diferentes tipos de servicios vehiculares.
    /// </summary>
    public partial class tbTipoServicios
    {
        public tbTipoServicios()
        {
            tbServicios = new HashSet<tbServicios>();
        }

        /// <summary>
        /// Identificador único del tipo de servicio.
        /// 
        /// </summary>
        public int IdTipoServicio { get; set; }
        /// <summary>
        /// Nombre o descripción del tipo de servicio.
        /// 
        /// </summary>
        public string Nombre { get; set; }
        /// <summary>
        /// Millaje recomendado para realizar el servicio.
        /// 
        /// </summary>
        public string MillajeCambioRecomendado { get; set; }
        /// <summary>
        /// Kilometraje recomendado para realizar el servicio.
        /// 
        /// </summary>
        public string KilometrajeCambioRecomendado { get; set; }
        /// <summary>
        /// Intervalo en meses recomendado para realizar el servicio.
        /// </summary>
        public decimal? Meses { get; set; }

        public virtual ICollection<tbServicios> tbServicios { get; set; }
    }
}