// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaseoExpressWebApp.Context
{
    /// <summary>
    /// Fecha de hasta el dia que pago
    /// </summary>
    public partial class tbTransacciones
    {
        public tbTransacciones()
        {
            IdServicios = new HashSet<tbServicios>();
        }

        public int IdTransaccion { get; set; }
        public string Imagen { get; set; }
        public int TarifaDiaria { get; set; }
        public int TarifaAhorro { get; set; }
        public int IdVehiculo { get; set; }
        public int? IdUsuario { get; set; }
        public DateTime FechaTransaccion { get; set; }
        public DateTime? FechaTransaccionHasta { get; set; }
        public bool Confirmada { get; set; }
        public int? UltimaSuma { get; set; }
        public string Comentario { get; set; }
        public int IdTipoTransaccion { get; set; }
        public DateTime FechaCreacion { get; set; }

        public virtual ICollection<tbServicios> IdServicios { get; set; }
    }
}