// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaseoExpressWebApp.Context
{
    public partial class tbUbicacionEnAutomovil
    {
        public int IdUbicacionEnAutomovil { get; set; }
        public string Ubicacion { get; set; }
    }
}