// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaseoExpressWebApp.Context
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            tbVehiculo = new HashSet<tbVehiculo>();
        }

        public int IdUsuario { get; set; }
        public string Imagen { get; set; }
        public int IdRol { get; set; }
        public string Nombre { get; set; }
        public string Identidad { get; set; }
        public string Cuenta { get; set; }
        public bool? EstaActivo { get; set; }

        public virtual tbRol IdRolNavigation { get; set; }
        public virtual ICollection<tbVehiculo> tbVehiculo { get; set; }
    }
}