// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaseoExpressWebApp.Context
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            tbTransacciones = new HashSet<tbTransacciones>();
            tbVehiculo = new HashSet<tbVehiculo>();
        }

        public int IdUsuario { get; set; }
        public int IdRol { get; set; }
        public string Nombre { get; set; }
        public string Identidad { get; set; }
        public string Cuenta { get; set; }
        public bool? EstaActivo { get; set; }

        public virtual tbRol IdRolNavigation { get; set; }
        public virtual ICollection<tbTransacciones> tbTransacciones { get; set; }
        public virtual ICollection<tbVehiculo> tbVehiculo { get; set; }
    }
}